### PR TITLE
Farming landingpage

### PR DESCRIPTION
**Pull request by solankitrushen**
I added the landing page for the farming website to the project. This includes all necessary files and assets for the layout. Live Demo ("https://htm-landing.vercel.app/")

### CODE REVIEW

**Comment by solankitrushen** [comment]
Hello @ianshulx,

I hope you're doing well! Just checking in on my pull request — is there any issue with it, or am I missing any guidelines? I'd really appreciate any suggestions or feedback to help improve it.

Thanks in advance!

**Comment by ianshulx** [comment]
Hey @solankitrushen , I noticed that your project is a bit advanced, which is awesome! However, since this is a beginner-friendly repo, it might be helpful to include some beginner-level contributions as well. Also, please try to optimize the size of any media files to keep the overall repo size manageable. This way, we can maintain a good balance and make the project more accessible to everyone. Thanks!

**Comment by solankitrushen** [comment]
Hi @ianshulx ,

Thank you for your feedback! I appreciate you pointing that out. I’ll definitely look into adding some beginner-level contributions and optimizing the media files to keep the repo size manageable. 

Would it be okay to add my repo once I make these adjustments?

Thanks again for your suggestions!

**Comment by ianshulx** [comment]
@solankitrushen definitely 👍

**Comment by solankitrushen** [comment]
What size is recommended for repository, @ianshulx?

**Pull request closed without merging**
